(cl:defpackage visp_hand2eye_calibration-srv
  (:use )
  (:export
   "COMPUTE_EFFECTOR_CAMERA"
   "<COMPUTE_EFFECTOR_CAMERA-REQUEST>"
   "COMPUTE_EFFECTOR_CAMERA-REQUEST"
   "<COMPUTE_EFFECTOR_CAMERA-RESPONSE>"
   "COMPUTE_EFFECTOR_CAMERA-RESPONSE"
   "COMPUTE_EFFECTOR_CAMERA_QUICK"
   "<COMPUTE_EFFECTOR_CAMERA_QUICK-REQUEST>"
   "COMPUTE_EFFECTOR_CAMERA_QUICK-REQUEST"
   "<COMPUTE_EFFECTOR_CAMERA_QUICK-RESPONSE>"
   "COMPUTE_EFFECTOR_CAMERA_QUICK-RESPONSE"
   "RESET"
   "<RESET-REQUEST>"
   "RESET-REQUEST"
   "<RESET-RESPONSE>"
   "RESET-RESPONSE"
  ))

