//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the visp_tracker package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __visp_tracker__MODELBASEDSETTINGSCONFIG_H__
#define __visp_tracker__MODELBASEDSETTINGSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace visp_tracker
{
  class ModelBasedSettingsConfigStatics;

  class ModelBasedSettingsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(ModelBasedSettingsConfig &config, const ModelBasedSettingsConfig &max, const ModelBasedSettingsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ModelBasedSettingsConfig &config1, const ModelBasedSettingsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ModelBasedSettingsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ModelBasedSettingsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ModelBasedSettingsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ModelBasedSettingsConfig &config) const = 0;
      virtual void getValue(const ModelBasedSettingsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T ModelBasedSettingsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (ModelBasedSettingsConfig::* field);

      virtual void clamp(ModelBasedSettingsConfig &config, const ModelBasedSettingsConfig &max, const ModelBasedSettingsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ModelBasedSettingsConfig &config1, const ModelBasedSettingsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ModelBasedSettingsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ModelBasedSettingsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ModelBasedSettingsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ModelBasedSettingsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ModelBasedSettingsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ModelBasedSettingsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, ModelBasedSettingsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<ModelBasedSettingsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ModelBasedSettingsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("angle_appear"==(*_i)->name){angle_appear = boost::any_cast<double>(val);}
        if("angle_disappear"==(*_i)->name){angle_disappear = boost::any_cast<double>(val);}
        if("mask_size"==(*_i)->name){mask_size = boost::any_cast<int>(val);}
        if("range"==(*_i)->name){range = boost::any_cast<int>(val);}
        if("threshold"==(*_i)->name){threshold = boost::any_cast<double>(val);}
        if("mu1"==(*_i)->name){mu1 = boost::any_cast<double>(val);}
        if("mu2"==(*_i)->name){mu2 = boost::any_cast<double>(val);}
        if("sample_step"==(*_i)->name){sample_step = boost::any_cast<double>(val);}
        if("strip"==(*_i)->name){strip = boost::any_cast<int>(val);}
        if("first_threshold"==(*_i)->name){first_threshold = boost::any_cast<double>(val);}
        if("mask_border"==(*_i)->name){mask_border = boost::any_cast<int>(val);}
        if("max_features"==(*_i)->name){max_features = boost::any_cast<int>(val);}
        if("window_size"==(*_i)->name){window_size = boost::any_cast<int>(val);}
        if("quality"==(*_i)->name){quality = boost::any_cast<double>(val);}
        if("min_distance"==(*_i)->name){min_distance = boost::any_cast<double>(val);}
        if("harris"==(*_i)->name){harris = boost::any_cast<double>(val);}
        if("size_block"==(*_i)->name){size_block = boost::any_cast<int>(val);}
        if("pyramid_lvl"==(*_i)->name){pyramid_lvl = boost::any_cast<int>(val);}
      }
    }

    double angle_appear;
double angle_disappear;
int mask_size;
int range;
double threshold;
double mu1;
double mu2;
double sample_step;
int strip;
double first_threshold;
int mask_border;
int max_features;
int window_size;
double quality;
double min_distance;
double harris;
int size_block;
int pyramid_lvl;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double angle_appear;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double angle_disappear;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int mask_size;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int range;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double threshold;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mu1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mu2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sample_step;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int strip;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double first_threshold;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int mask_border;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int max_features;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int window_size;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double quality;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_distance;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double harris;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int size_block;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int pyramid_lvl;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ModelBasedSettingsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ModelBasedSettingsConfig &__max__ = __getMax__();
      const ModelBasedSettingsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ModelBasedSettingsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ModelBasedSettingsConfig &__getDefault__();
    static const ModelBasedSettingsConfig &__getMax__();
    static const ModelBasedSettingsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const ModelBasedSettingsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void ModelBasedSettingsConfig::ParamDescription<std::string>::clamp(ModelBasedSettingsConfig &config, const ModelBasedSettingsConfig &max, const ModelBasedSettingsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class ModelBasedSettingsConfigStatics
  {
    friend class ModelBasedSettingsConfig;

    ModelBasedSettingsConfigStatics()
    {
ModelBasedSettingsConfig::GroupDescription<ModelBasedSettingsConfig::DEFAULT, ModelBasedSettingsConfig> Default("Default", "", 0, 0, true, &ModelBasedSettingsConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.angle_appear = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.angle_appear = 90.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.angle_appear = 65.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("angle_appear", "double", 0, "Maximal angle value to consider an appearing face", "", &ModelBasedSettingsConfig::angle_appear)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("angle_appear", "double", 0, "Maximal angle value to consider an appearing face", "", &ModelBasedSettingsConfig::angle_appear)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.angle_disappear = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.angle_disappear = 90.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.angle_disappear = 75.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("angle_disappear", "double", 0, "Minimal angle value to consider that a face disappear", "", &ModelBasedSettingsConfig::angle_disappear)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("angle_disappear", "double", 0, "Minimal angle value to consider that a face disappear", "", &ModelBasedSettingsConfig::angle_disappear)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mask_size = 3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mask_size = 15;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mask_size = 7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<int>("mask_size", "int", 0, "mask size", "", &ModelBasedSettingsConfig::mask_size)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<int>("mask_size", "int", 0, "mask size", "", &ModelBasedSettingsConfig::mask_size)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.range = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.range = 50;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.range = 5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<int>("range", "int", 0, "range", "", &ModelBasedSettingsConfig::range)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<int>("range", "int", 0, "range", "", &ModelBasedSettingsConfig::range)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.threshold = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.threshold = 20000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.threshold = 2000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("threshold", "double", 0, "threshold", "", &ModelBasedSettingsConfig::threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("threshold", "double", 0, "threshold", "", &ModelBasedSettingsConfig::threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mu1 = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mu1 = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mu1 = 0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("mu1", "double", 0, "contrast continuity (mu1)", "", &ModelBasedSettingsConfig::mu1)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("mu1", "double", 0, "contrast continuity (mu1)", "", &ModelBasedSettingsConfig::mu1)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mu2 = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mu2 = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mu2 = 0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("mu2", "double", 0, "contrast continuity (mu2)", "", &ModelBasedSettingsConfig::mu2)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("mu2", "double", 0, "contrast continuity (mu2)", "", &ModelBasedSettingsConfig::mu2)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sample_step = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sample_step = 50.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sample_step = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("sample_step", "double", 0, "sample step", "", &ModelBasedSettingsConfig::sample_step)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("sample_step", "double", 0, "sample step", "", &ModelBasedSettingsConfig::sample_step)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.strip = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.strip = 10;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.strip = 2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<int>("strip", "int", 0, "strip", "", &ModelBasedSettingsConfig::strip)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<int>("strip", "int", 0, "strip", "", &ModelBasedSettingsConfig::strip)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.first_threshold = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.first_threshold = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.first_threshold = 0.4;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("first_threshold", "double", 0, "good samples remaining threshold before reinitialization (edge)", "", &ModelBasedSettingsConfig::first_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("first_threshold", "double", 0, "good samples remaining threshold before reinitialization (edge)", "", &ModelBasedSettingsConfig::first_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mask_border = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mask_border = 50;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mask_border = 5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<int>("mask_border", "int", 0, "Face dead zone size", "", &ModelBasedSettingsConfig::mask_border)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<int>("mask_border", "int", 0, "Face dead zone size", "", &ModelBasedSettingsConfig::mask_border)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_features = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_features = 30000;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_features = 10000;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<int>("max_features", "int", 0, "Maximum number of KLT features", "", &ModelBasedSettingsConfig::max_features)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<int>("max_features", "int", 0, "Maximum number of KLT features", "", &ModelBasedSettingsConfig::max_features)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.window_size = 3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.window_size = 7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.window_size = 5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<int>("window_size", "int", 0, "Window size arround a KLT point", "", &ModelBasedSettingsConfig::window_size)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<int>("window_size", "int", 0, "Window size arround a KLT point", "", &ModelBasedSettingsConfig::window_size)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.quality = 0.0001;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.quality = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.quality = 0.05;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("quality", "double", 0, "Quality threshold used to consider that a point is valid", "", &ModelBasedSettingsConfig::quality)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("quality", "double", 0, "Quality threshold used to consider that a point is valid", "", &ModelBasedSettingsConfig::quality)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_distance = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_distance = 50.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_distance = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("min_distance", "double", 0, "Min distance between two points", "", &ModelBasedSettingsConfig::min_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("min_distance", "double", 0, "Min distance between two points", "", &ModelBasedSettingsConfig::min_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.harris = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.harris = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.harris = 0.01;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("harris", "double", 0, "Harris value", "", &ModelBasedSettingsConfig::harris)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<double>("harris", "double", 0, "Harris value", "", &ModelBasedSettingsConfig::harris)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.size_block = 2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.size_block = 10;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.size_block = 3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<int>("size_block", "int", 0, "Block size", "", &ModelBasedSettingsConfig::size_block)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<int>("size_block", "int", 0, "Block size", "", &ModelBasedSettingsConfig::size_block)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pyramid_lvl = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pyramid_lvl = 5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pyramid_lvl = 3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<int>("pyramid_lvl", "int", 0, "Number of levels in the pyramid", "", &ModelBasedSettingsConfig::pyramid_lvl)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr(new ModelBasedSettingsConfig::ParamDescription<int>("pyramid_lvl", "int", 0, "Number of levels in the pyramid", "", &ModelBasedSettingsConfig::pyramid_lvl)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ModelBasedSettingsConfig::AbstractGroupDescriptionConstPtr(new ModelBasedSettingsConfig::GroupDescription<ModelBasedSettingsConfig::DEFAULT, ModelBasedSettingsConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<ModelBasedSettingsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ModelBasedSettingsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ModelBasedSettingsConfig __max__;
    ModelBasedSettingsConfig __min__;
    ModelBasedSettingsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ModelBasedSettingsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ModelBasedSettingsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ModelBasedSettingsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const ModelBasedSettingsConfig &ModelBasedSettingsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const ModelBasedSettingsConfig &ModelBasedSettingsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const ModelBasedSettingsConfig &ModelBasedSettingsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<ModelBasedSettingsConfig::AbstractParamDescriptionConstPtr> &ModelBasedSettingsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ModelBasedSettingsConfig::AbstractGroupDescriptionConstPtr> &ModelBasedSettingsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ModelBasedSettingsConfigStatics *ModelBasedSettingsConfig::__get_statics__()
  {
    const static ModelBasedSettingsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ModelBasedSettingsConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __MODELBASEDSETTINGSRECONFIGURATOR_H__
